services:

  dynamo:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"

  game-be:
    build:
      context: game-be
      target: build
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    volumes:
     - ./game-be/:/app
     - /app/node_modules
    ports:
     - 4000:4000
    command: npm run dev

  game-fe:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - "./H2HAdventure/target/H2HAdventure2P:/usr/share/nginx/html"
