services:

  dynamo:
    image: "amazon/dynamodb-local:latest"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    ports:
      - "8000:8000"
    volumes:
      - "./tmp/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  game-be:
    build:
      context: game-be
      target: build
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    volumes:
      - ./game-be/:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      LOG_LEVEL: DEBUG
    ports:
      - 4000:80
    command: npm run dev

  game-fe:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - "./H2HAdventure/target:/usr/share/nginx/html"
