$ Standoff against bat w/ dragon 

$ Hide Other Dragons
Send "DM 0 0 80 32 2 2 0 77" on frame #128
Send "DM 0 0 80 32 2 2 1 77" on frame #128

$ Setup player 2 with bat and red dragon
Sent "PM 1 2 221 154 0 0" on frame #210
Sent "BP 1 7 9 0 -1 0 0 0" on frame #210
Sent "PP 1 17 0 -5 -1 0 0 0" on frame #213

$ Player 1 brings chalice and stops
Sent "PM 0 1 57 124 6 0" on frame #200
Sent "PP 0 19 0 -8-1 0 0 0" on frame #203
Sent "PM 0 2 47 124 0 0" on frame #355

.