# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "lobby-be-prod"
parameter_overrides = "EnvironmentType=\"Prod\""

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
s3_prefix = "lobby-be-prod"
resolve_s3 = true
image_repositories = []

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"
parameter_overrides = "EnvironmentType=\"Dev\""

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
parameter_overrides = "EnvironmentType=\"Dev\""


[prod.global.parameters]
stack_name = "lobby-be-prod"
parameter_overrides = "EnvironmentType=\"Prod\""

[prod.deploy.parameters]
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
s3_prefix = "lobby-be-prod"
resolve_s3 = true

[test.global.parameters]
stack_name = "lobby-be-test"
parameter_overrides = "EnvironmentType=\"Test\""

[test.deploy.parameters]
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
s3_prefix = "lobby-be-test"
resolve_s3 = true
