# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  lobby-be

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

Parameters:
  EnvironmentType:
    Description: Environment.  Either 'production' or 'development'
    Type: String

Globals:
    Function:
        Environment:
            Variables:
                ENVIRONMENT_TYPE: !Ref EnvironmentType
    Api:
        Cors:
            AllowMethods: "'GET,POST,PUT,OPTIONS'"
            AllowHeaders: "'Content-Type'"
            AllowOrigin: "'*'"
            # AllowCredentials: true  Uncomment only if you choose a specific origin instead of the * wildcard.
            
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction


  ###########################
  # Lambdas for Player management
  #
  getAllPlayersFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-all-players.getAllPlayersHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Return a list of all registered players
      Policies:
        # Give Create/Read/Update/Delete Permissions
        - DynamoDBReadPolicy:
            TableName: !Ref PlayersTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /player/
            Method: GET

  putPlayerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/put-player.putPlayerHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Register a player is currently online
      Policies:
        # Give Create/Read/Update/Delete Permissions
        - DynamoDBCrudPolicy:
            TableName: !Ref PlayersTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /player/{name}
            Method: PUT

  ###########################
  # Lambdas for Game management
  #
  getAllGamesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-all-games.getAllGamesHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Return a list of all registered players
      Policies:
        # Give Create/Read/Update/Delete Permissions
        - DynamoDBReadPolicy:
            TableName: !Ref GamesTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /game
            Method: GET

  getGameFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-game.getGameBySessionHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Get a configuration setting
      Policies:
        # Give Create/Read/Update/Delete Permissions
        - DynamoDBReadPolicy:
            TableName: !Ref GamesTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /game/{session}
            Method: GET

  createGameFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/create-game.createGameHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Register a game
      Policies:
        # Give Create/Read/Update/Delete Permissions
        - DynamoDBCrudPolicy:
            TableName: !Ref GamesTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /newgame
            Method: POST

  createGameServerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/create-game-server.createGameServerHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Spawn a game server
      Policies:
        # Give Create/Read/Update/Delete Permissions
        - DynamoDBCrudPolicy:
            TableName: !Ref SettingsTable
        - EcsRunTaskPolicy:
            TaskDefinition: "h2hadv-serverTaskDefinition*"
        - Statement:
          - Sid: PassRolePolicy
            Effect: Allow
            Action:
            - "iam:PassRole"
            Resource:
            - "arn:aws:iam::637423607158:role/h2hadv*"

      Events:
        Api:
          Type: Api
          Properties:
            Path: /newgameserver
            Method: POST
      Environment:
        Variables:
          CUSTOM_DOMAIN_URL: !Sub CustomDomainUrl

  putGameFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/put-game.putGameHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Update an existing game
      Policies:
        # Give Create/Read/Update/Delete Permissions
        - DynamoDBCrudPolicy:
            TableName: !Ref GamesTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /game/{session}
            Method: PUT

  ###########################
  # Convenience method for getting all player, game and chat updates
  #
  getLobbyState:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-lobby-state.getLobbyStateHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Get current users, games, and latest chat
      Policies:
        # Give Create/Read/Update/Delete Permissions
        - DynamoDBReadPolicy:
            TableName: !Ref PlayersTable
        - DynamoDBReadPolicy:
            TableName: !Ref GamesTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /lobby
            Method: GET

  ###########################
  # Lambdas for Settings management
  #
  getSettingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-setting.getSettingByNameHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Get a configuration setting
      Policies:
        # Give Create/Read/Update/Delete Permissions
        - DynamoDBReadPolicy:
            TableName: !Ref SettingsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /setting/{setting_name}
            Method: GET
  
  putSettingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/put-setting.putSettingHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Set a configuration setting
      Policies:
        # Give Create/Read/Update/Delete Permissions
        - DynamoDBCrudPolicy:
            TableName: !Ref SettingsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /setting/{setting_name}
            Method: PUT

  deleteSettingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/delete-setting.deleteSettingHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Delete a configuration setting
      Policies:
        # Give Create/Read/Update/Delete Permissions
        - DynamoDBCrudPolicy:
            TableName: !Ref SettingsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /setting/{setting_name}
            Method: DELETE


  # Players table
  #  Table of recent players and when they played.  Players that haven't played recently 
  #  are deleted from this table.  More permanent and more detailed info on players is kept
  #  in a different table, the PlayersDetails table.
  #
  #  playername (primary key): string - username of the player
  #  lastactive: number - timestamp of last time they were in the lobby or playing the game
  #  ttl: number - timestamp at which this player can be removed from this table
  #
  PlayersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: Players
      PrimaryKey:
        Name: playername
        Type: String

  # Games table
  #  Table of proposed and active games.  Past games are deleted from this table.
  #
  #  session (primary key): string - unique key assigned to the game
  #  game_number: number - 0,1,2 indicating whether Game 1, 2 or 3
  #  number_players: number - 2, 2.5, or 3 indicating whether to have exactly 2 players, 2 or 3, or exactly 3
  #  fast_dragons: boolean - whether dragons are fast or slow
  #  fearful_dragons: boolean - whether dragons frun from sword
  #  player_names: string[] - array of player names
  #  
  GamesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: Games
      PrimaryKey:
        Name: session
        Type: Number

  # Settings table
  #  Table of name value settings of the system.  At time of creation "game_server_ip" is the only
  #  setting
  #
  #  setting_name (primary key): string
  #  setting_value: string
  #  time_set: number - the timestamp of when this setting was last changed
  #
  SettingsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: Settings
      PrimaryKey:
        Name: setting_name
        Type: String

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
