name: Docker Stuff

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check the username length
      run: echo ${{ secrets.DOCKERHUB_USERNAME }} | wc
    - name: Check the token length
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | wc
    - name: Check the first half of username
      run:  export VAL=`echo ${{ secrets.DOCKERHUB_USERNAME }}` && echo $VAL | wc
