name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Load Source
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        working-directory: ./game-be
        run: docker build . --tag roanders/h2hadv-server
      - name: Tag the Docker image
        working-directory: ./game-be
        run: docker tag roanders/h2hadv-server roanders/h2hadv-server
      - name: Deploy the Docker image
        working-directory: ./game-be
        run: docker push roanders/h2hadv-server
